### ISSUE TITLE
Can run the demo

### ISSUE THREAD

**Issue by ArrowBaZ** [thebrubaker/vue-element-queries#2]
Hello,

After `git clone`, `npm i` and `vue build example`
I get error un the console 

`Cannot read property '_lifecycleHooks' of undefined`

Same if I used the Plugin file in root folder

**Comment by thebrubaker** [comment]
Hmmm I just did the same and it worked. What version of node are you running?

**Comment by ArrowBaZ** [comment]
```
$ node -v
v8.1.4
$ npm -v
5.3.0
$ vue --version
2.8.1
```

I'm on Windows (sorry for that, Company recommendation..)

**Comment by thebrubaker** [comment]
I just pushed an update to the example to use the new vue-cli tool that has `vue serve ./example` and possibly that will work, if you're still interested.
