### ISSUE TITLE
any plans to maintain?

### ISSUE THREAD

**Issue by eybarta** [thebrubaker/vue-element-queries#4]
Hi, I've successfully used this plugin in 2 projects.. love it.

My issue is I can't get this to work at all on IE.. is there any way to make it work?

thnx!

**Comment by thebrubaker** [comment]
Awesome glad to hear you found it useful! I’ll take a look and see what I
can find out.

**Comment by eybarta** [comment]
Hi @thebrubaker , have you had a chance to take a look and see if there's a way to adapt
this plugin for IE? thanks.

**Comment by thebrubaker** [comment]
I'm not super big on IE debugging (I also don't have a windows machine to test on). Could this be something you look into and submit a PR on? Happy to collaborate on it.

**Comment by thebrubaker** [comment]
What version of IE? The newest version of css element queries dropped IE9 and lower support. That may be the issue. This type of package isn't going to be friendly to legacy browsers.

**Comment by eybarta** [comment]
@thebrubaker I would think IE11 > is good enough.. in the meanwhile I resorted to using the ResizeObserver API and a computed value for element width to have a cross-browser solution.. When I have more time I'll take a look on how to make this plugin work and PR it.. thx
